name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test || true  # Allow failures

      - name: Install Allure CLI
        run: npm install -g allure-commandline  # Ensure Allure is installed

      - name: Generate Allure Report
        run: allure generate allure-results -o allure-report --clean

      - name: Serve Allure Report in GitHub Actions
        run: |
          npx http-server allure-report -p 8080 &
          sleep 5
        continue-on-error: true  # Ensure workflow doesn't stop

      - name: Expose Report URL
        run: |
          echo "🔗 View Allure Report: http://localhost:8080"
